profilewebsite/urls.py
from django.urls import path
from . import views


app_name = 'story4'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('experience/', views.experience, name='experience'),
    path('abilities/', views.abilities, name='abilities'),
    path('contact/', views.contact, name='contact'),
    path('schedule/', views.schedule, name='schedule'),
    path('view_schedule/', views.view_schedule, name='view_schedule'),
    path('add_schedule/', views.add_schedule, name='add_schedule'),
    path('delete/', views.delete, name="delete"),   
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profilewebsite.urls')),
]

profilewebsite/models.py
from django.db import models

# Create your models here.

class Schedule(models.Model):
    date_time = models.DateTimeField('date_time')
    date_end = models.DateTimeField('date_end')
    category = models.CharField(max_length=50, default = "")
    activity = models.CharField(max_length=50, default = "")
    location = models.CharField(max_length=50, default = "")

profilewebsite/forms.py
from django import forms
from .models import Schedule
from django.forms import ModelForm

class ScheduleForm(forms.Form):
    date_time = forms.DateTimeField(input_formats=['%Y-%m-%dT%H:%M'])
    date_end = forms.DateTimeField(input_formats=['%Y-%m-%dT%H:%M'])
    category = forms.CharField(max_length=50)
    activity = forms.CharField(max_length=50)
    location = forms.CharField(max_length=50)

profilewebsite/views.py
from django.shortcuts import render
from .forms import ScheduleForm
from .models import Schedule
from django.shortcuts import redirect
import datetime


# Create your views here.
def home(request):
    return render(request, 'home.html')

def profile(request):
    return render(request, 'profile.html')

def abilities(request):
    return render(request, 'abilities.html')

def experience(request):
    return render(request, 'experience.html')

def contact(request):
    return render(request, 'contact.html')

def schedule(request):
    list_sched = Schedule.objects.all().values()
    return render(request, 'sched_form.html', {'sched' : list_sched})

def add_schedule(request):
    if request.method == 'POST' :
        print("hai")
        form = ScheduleForm(request.POST)
        if form.is_valid():
            date_time = form.data['date_time']
            date_end = form.data['date_end']
            category = form.data['category']
            activity = form.data['activity']
            location = form.data['location']
            sched = Schedule(activity=activity,date_time=date_time, date_end=date_end, category=category, location=location)
            sched.save()
    return redirect('/view_schedule/')

def view_schedule(request):
    list_sched = Schedule.objects.all().values()
    return render(request, 'sched_edit.html', {'sched' : list_sched})

def delete(request):
	if request.method == 'POST'  :
		id = request.POST['id']
		Schedule.objects.filter(id=id).delete()
	return redirect('/view_schedule')

profilewebsite/templates/abilities.html
{% extends "base.html" %}
{% load static %} 
{% block title %}Shafira Ayu Maharani | Abilities{% endblock %} 
   

{% block content %}
          <div class="sect-abilities" id ="abilities">
                <div class="container">
                    <h1 class="text-center title pt-5 pb-5"><br><b>Abilities</b></h1>
                    <div class="row">
                      <div class="col-sm-6" style="padding-left: 15%;">
                        <h2 class="text-left"><b>Skills</b></h2><br>
                        <h4 class="text-left">Python</h4>
                        <span class="dot-pink"></span>
                        <span class="dot-pink"></span>
                        <span class="dot-pink"></span>
                        <span class="dot-pink"></span>
                        <span class="dot"></span><br>
                        <h4 class="text-left">Java</h4>
                        <span class="dot-pink"></span>
                        <span class="dot-pink"></span>
                        <span class="dot-pink"></span>
                        <span class="dot"></span>
                        <span class="dot"></span><br>
                        <h4 class="text-left">HTML</h4>
                        <span class="dot-pink"></span>
                        <span class="dot-pink"></span>
                        <span class="dot-pink"></span>
                        <span class="dot"></span>
                        <span class="dot"></span><br>
                        <h4 class="text-left">CSS</h4>
                        <span class="dot-pink"></span>
                        <span class="dot-pink"></span>
                        <span class="dot-pink"></span>
                        <span class="dot"></span>
                        <span class="dot"></span><br>
                        <h4 class="text-left">Ruby</h4>
                        <span class="dot-pink"></span>
                        <span class="dot"></span>
                        <span class="dot"></span>
                        <span class="dot"></span>
                        <span class="dot"></span><br>
                      </div>
                      <div class="col-sm-6" style="padding-left: 15%;">
                          <h2 class="text-left"><b>Languages</b></h2><br>
                          <h4 class="text-left">Indonesia</h4>
                          <span class="dot-pink"></span>
                          <span class="dot-pink"></span>
                          <span class="dot-pink"></span>
                          <span class="dot-pink"></span>
                          <span class="dot-pink"></span><br>
                          <h4 class="text-left">English</h4>
                          <span class="dot-pink"></span>
                          <span class="dot-pink"></span>
                          <span class="dot-pink"></span>
                          <span class="dot"></span>
                          <span class="dot"></span><br>
                          <h4 class="text-left">Japanesse</h4>
                          <span class="dot-pink"></span>
                          <span class="dot"></span>
                          <span class="dot"></span>
                          <span class="dot"></span>
                          <span class="dot"></span><br>
                          <h4 class="text-left">Germany</h4>
                          <span class="dot-pink"></span>
                          <span class="dot"></span>
                          <span class="dot"></span>
                          <span class="dot"></span>
                          <span class="dot"></span><br>
                      </div>
                    </div>
                </div>
              </div>
              {% endblock %}

        

profilewebsite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/fira.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg fixed-top navbar-light" style="background-color:  #D7DBDD; color: #34495E; font-size: 20px;">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
              
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item navfont">
                <a class="nav-link" href="{% url 'story4:home' %}"><b>HOME</b></a>
                </li>
                <li class="nav-item navfont">
                    <a class="nav-link" href="{% url 'story4:profile' %}"><b>PROFILE</b></a>
                </li>
                <li class="nav-item navfont">
                    <a class="nav-link" href="{% url 'story4:experience' %}"><b>EXPERIENCE</b></a>
                </li>
                <li class="nav-item navfont">
                    <a class="nav-link" href="{% url 'story4:abilities' %}"><b>ABILITIES</b></a>
                </li>
                <li class="nav-item navfont">
                    <a class="nav-link" href="{% url 'story4:contact' %}"><b>CONTACT</b></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <b>SCHEDULE</b>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'story4:schedule' %}">Add Schedule</a>
                      <a class="dropdown-item" href="{% url 'story4:view_schedule' %}">See Schedule</a> 
                    </div>
                  </li>
                
               
            </div>
        </nav>
        {% block content %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        {% block script %}{% endblock %}
    </body>
</html>

profilewebsite/templates/contact.html
{% extends "base.html" %}
{% load static %} 
{% block title %}Shafira Ayu Maharani | Contact{% endblock %} 
   

{% block content %}
          <div class="sect-experience" id="contact">
                <div class="container">
                  <h1 class="text-center title pt-5 pb-5"><br><b>Contact</b></h1>
                  <div class="row size">
                    <div class="col-sm-12 col-md-6" id = "kecil">
                        <div class="text-left">
                          <a href="mailto:a.maharanishafira@gmail.com" target="_blank">
                          <img src="{% static 'images/gmail.png' %}" alt="gmail" class="mr-5" width="30%">
                          <b style="color: black;">a.maharanishafira@gmail.com</b>
                          </a>
                        </div>
                        <div class="text-left mt-5">
                            <a href="https://www.instagram.com/shafirayu_mh" target="_blank">
                            <img src="{% static 'images/instagram.png' %}" alt="instagram" class="mr-5" width="30%">
                            <b style="color: black;">@shafirayu_mh</b>
                            </a>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6" id = "kecil">
                        <div class="text-left">
                          <a href=https://www.twitter.com/@shafira_ayu12/" target="_blank">
                          <img src="{% static 'images/twitter.png' %}" alt="twitter" class="mr-5" width="30%">
                          <b style="color: black;">@shafira_ayu12</b>
                          </a>
                        </div>
                        <div class="text-left mt-5">
                            <a href="https://www.linkedin.com/in/shafira-ayu-004a78171" target="_blank">
                            <img src="{% static 'images/linkedin.png' %}" alt="linkedin" class="mr-5" width="30%">
                            <b style="color: black;">Shafira Ayu Maharani</b>
                            </a>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endblock %}
         

profilewebsite/templates/experience.html
{% extends "base.html" %}
{% load static %} 
{% block title %}Shafira Ayu Maharani | Experience{% endblock %} 
   

{% block content %}
          <div class="sect-experience" id ="experience">
                <div class="container">
                    <h1 class="text-center title pt-5 pb-5"><br><b>Experience</b></h1>
                    <div class="row">
                        <div class="col-sm-12 col-md-6">
                            <h2 class="text-left"><b>Education</b></h2>
                          <div class="timeline">
                            <div class="cont right">
                              <div class="fill">
                                  <h3 class="text-left">Information System - University of Indonesia</h3>
                                  <h6 class="text-left">August 2018 - Current</h6>
                                  <p class="text-left">The course that I have completed : Math Discrete 1 & 2, Calculus 1, Programming Foundation 1 & 2, Computer Architecture Foundation,  Information System Principles.</p>
    
                              </div>
                            </div>
                            <div class="cont right">
                                <div class="fill">
                                    <h3 class="text-left">Science - 2 Senior High School</h3>
                                    <h6 class="text-left">July 2015 - July 2018</h6>
                                    
                                </div>
                              </div>
                          </div>
                        </div>
                        
                        <div class="col-sm-12 col-md-6">
                          <h2 class="text-left"><b>Organization</b></h2>
                            <div class="timeline">
                              <div class="cont right">
                                <div class="fill">
                                  <h3 class="text-left">FUKI - Fasilkom UI</h3>
                                  <h6 class="text-left">Feb 2019 - Current</h6>
                                  <p class="text-left">FUKI (Forum Ukhuwah & Kajian Islam) is Dakwah Institute at Faculty of Computer Science. I became a Public Relation Division Staff.</p>
      
                                </div>
                              </div>
                              <div class="cont right">
                                  <div class="fill">
                                    <h3 class="text-left">SIWAK-NG - Fasilkom UI</h3>
                                    <h6 class="text-left">May 2019 - Current</h6>
                                    <p class="text-left">SIWAK-NG (Studi Islam Awal Tahun Next Generation) is an annual event to welcome Muslim faculty of Computer Science new students. I became Vice Peson In Charge of Public Relation Division.</p>
        
                                  </div>
                                </div>
                                <div class="cont right">
                                    <div class="fill">
                                      <h3 class="text-left">COMPFEST 11 - Fasilkom UI</h3>
                                      <h6 class="text-left">March 2019 - Current</h6>
                                      <p class="text-left">COMPFEST (Computer Festival) is the biggest IT event held by students. I became Staff at Software Engineering Academy.</p>
          
                                    </div>
                                  </div>
                            </div>
                          </div>
                          </div>    
                    </div>
                </div>
            </div>
            {% endblock %}

profilewebsite/templates/home.html
{% extends "base.html" %}
{% load static %} 
{% block title %}Shafira Ayu Maharani | Home{% endblock %} 
   

{% block content %}
        <div class="sect-header" id ="home">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        
                        <h1 class="text-center" id="head" style="color:#34495E;"><b>Hello,<br>I'm Fira!</b></h1>
                        <h2 class="text-center" id="text"  style="color:#34495E;">Let's find out more about me!</h2>
                    </div>    
                </div>
            </div>
        </div>
        {% endblock %}

profilewebsite/templates/profile.html
{% extends "base.html" %}
{% load static %} 
{% block title %}Shafira Ayu Maharani | Profile{% endblock %} 
   

{% block content %}
          <div class="sect-profile" id="profile">
                <div class="container">
                  <h1 class="text-center title pt-5 pb-5"><br><b>Profile</b></h1>
                  <div class="row">
                    <div class="col-sm-12 col-md-4">
                      <h2 class="text-left"><b>About Me</b></h2>
                      <h4 class="text-left">I'm an Information System student in Faculty of Computer Science Universitas Indonesia 2018. I like to study something new and I love to be helpful person for others.</h4>
                    </div>
      
                    <div class="col-sm-12 col-md-4">
                      <!-- Trigger the Modal -->
                      <img src="{% static 'images/foto2.jpg' %}" alt="foto fira"  style ="width :300px; border-radius: 100%;">
                    </div>
      
                    <div class="col-sm-12 col-md-4">
                      <h2 class="text-left"><b>Details</b></h2>
                      <h4 class="text-left">
                        <strong>Name</strong><br>
                          Shafira Ayu Maharani
                          <br><br>
                          <strong>Birth Place</strong><br>
                          Jakarta
                          <br><br>
                          <strong>Birth Date</strong><br>
                          2 March 2000
                          <br><br>
                          <strong>Location</strong><br>
                          Indonesia
                      </h4>
                    </div>
                    
                  </div>
                </div>
              </div>
{% endblock %}

profilewebsite/templates/sched_edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Shafira Ayu Maharani | Edit Schedule{% endblock %} 

{% block content %}
<div class="sect-experience">
    <div class="container">
        <h1 class="text-center title pt-5 pb-5"><br><b>Schedule</b></h1>
        <br>
        <div class="col-md-12 left">
            <a href="{% url 'story4:schedule' %}"><button data-toggle="modal" data-target="#con-close-modal" class="btn btn-outline-dark" style="float: right !important; margin-right: 10px;">➕</button></a>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Activity</th>
                        <th scope="col">Start Time</th>
                        <th scope="col">End Time</th>
                        <th scope="col">Location</th>
                        <th scope="col">Category</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in sched %}
                    <tr>
                        <td>{{ i.activity }}</td>
                        <td>{{ i.date_time }}</td>
                        <td>{{ i.date_end }}</td>
                        <td>{{ i.location }}</td>
                        <td>{{ i.category }}</td>
                        <td><form action = "/delete/" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ i.id }}"> 
                            <button type ="submit"class="btn btn-outline-danger">❌</button>
                          </form></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

</div>
{% endblock %}

profilewebsite/templates/sched_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Shafira Ayu Maharani | Add Schedule{% endblock %} 

{% block content %}
<div class="sect-profile">
  <div class="container">
    <h1 class="text-center title pt-5 pb-5"><br><b>Add Schedule</b></h1>
      <form action= "{% url 'story4:add_schedule' %}" method="POST">
      {% csrf_token %}
        <div class="form-group">
          <label>Activity</label>
          <input name="activity" type="text" class="form-control" placeholder="Enter your activity"> 
        </div>
        <div class="form-group">
          <label>Date Time</label>
          <input name="date_time" type="datetime-local" class="form-control" placeholder="Enter your date and time"> 
        </div>
        <div class="form-group">
          <label>Date Time End</label>
          <input name="date_end" type="datetime-local" class="form-control" placeholder="Enter your date and time"> 
        </div>
        <div class="form-group">
          <label>Location</label>
          <input name="location" type="text" class="form-control" placeholder="Enter your location"> 
        </div>
        <div class="form-group">
          <label>Category</label>
          <input name="category" type="text" class="form-control" placeholder="Enter category"> 
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>

      
  </div>
</div>
    
{% endblock %}